spring.application.name=Academy-Manager
server.address=0.0.0.0
spring.datasource.url=jdbc:mysql://${DB_HOST:127.0.0.1}:${DB_PORT:3306}/${DB_NAME:school-test}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASS:test123}
spring.jpa.hibernate.ddl-auto=update
jwt.secret=myOveryOlongObase64OencodedOSEcRETOthatOisOatOleastO32ObytesOlong
jwt.access-token-expiration=1200000
jwt.refresh-token-expiration=1800000
telegram.bot.token=8925816885:AAHK-3n8FLZHtdtCADjgy7vbl_z7Js8vcxk

